### ISSUE TITLE
Compatibility with ESPHome

### ISSUE THREAD

**Issue by amotl** [daq-tools/kotori#67]
Hi there,

friends of Kotori recently started playing with the excellent [ESPHome] by @OttoWinter and contributors (cheers!). It would be sweet to add a corresponding page to the documentation which outlines best practices how both software components can be made work together, based on ESPHome's [mqtt.publish_json Action].

It looks pretty straight-forward, yet we will have to figure out how to embed the timestamp ([Time]) into the MQTT payload.

With kind regards,
Andreas.

[ESPHome]: https://github.com/esphome/esphome
[mqtt.publish_json Action]: https://esphome.io/components/mqtt.html#mqtt-publish-json-action
[Time]: https://esphome.io/components/time.html

**Comment by amotl** [comment]
https://github.com/esphome/esphome/pull/719 gives some clues, here it would be for HTTP telemetry, but it can surely be applied to MQTT as well:

```yaml
- http_request.post:
    url: https://api.telegram.org/bot<BOT_ID>:<BOT_SECRET>/sendMessage
    headers:
      Content-Type: application/json
      X-Custom-Header: !lambda |-
        return "hValue";
    json:
      chat_id: <CHAT_ID>
      disable_web_page_preview: 1
      text: !lambda |-
        char str[20];
        time_t currTime = id(sntp_time).now().timestamp;
        strftime(str, sizeof(str), "%Y-%m-%d %H:%M:%S", localtime(&currTime));
        return (std::string) "Current time is " + str;
```

It looks like this example uses [Templates (Lambdas)]:

> With templates inside ESPHome, you can do almost everything.

However, using the non-lambda approach like outlined above, could this work as well in order to bring the current value of the [SNTP Time Source] into the outbound MQTT payload?

```yaml
- mqtt.publish_json:
    topic: amazonas/ecuador/cuyabeno/node-01/data.json
    payload: |-
      root["key"] = id(my_sensor).state;
      root["time"] = id(sntp_time).now().timestamp;
      root["greeting"] = "Hello World";
```

[Templates (Lambdas)]: https://esphome.io/guides/automations.html#templates-lambdas
[SNTP Time Source]: https://esphome.io/components/time.html#sntp-time-source

**Comment by amotl** [comment]
We just heard back from the workbench that this snippet works well:
```yaml

time:
  - platform: sntp
    id: sntp_time

mqtt:
  broker: foobar
  on_message:
    - topic: esp32/bme280
      payload: "status"
      qos: 0
      then:
        - mqtt.publish_json:
            topic: workbench/testdrive/area-42/evb-ea-ind-02/data.json
            payload: |-
              root["time"] = id(sntp_time).now().timestamp;
              root["bme280_temp"] = id(bme280_temperature).state;
              root["bme280_humidity"] = id(bme280_humidity).state;
              root["bme280_pressure"] = id(bme280_pressure).state;
```

Thanks for sharing!

**Comment by amotl** [comment]
As a newcomer to ESPHome, I am interested in some more details: I see from the configuration snippet above that
```yaml
on_message:
  - topic: esp32/bme280
```

Does that mean that the outbound message is only submitted when an inbound message to the MQTT topic `esp32/bme280` has been received.

Would there also be a way to make the ESPHome firmware publish those measurements periodically?

**Comment by amotl** [comment]
Finding the relevant information was easy. The [on_time Trigger] component of ESPHome will enable to run all actions as cronjobs, like:
```yaml
time:
  - platform: sntp
    on_time:

      # Cron syntax, trigger every 5 minutes
      - cron: '* /5 * * * *'
        then:
          - switch.toggle: my_switch
```

Kudos again to @OttoWinter for conceiving this excellent framework!

[on_time Trigger]: https://esphome.io/components/time.html#time-on-time

**Comment by amotl** [comment]
Now, it would be sweet to get a full working example how to bring both details (sensor reading & MQTT publishing vs. periodic actions) together, either based on the `interval` component or the `on_time` trigger.

Maybe those would work already? I will be happy to receive feedback.

### Using `interval`
```yaml
time:
  - platform: sntp
    id: sntp_time

interval:
  - interval: 5min
    then:
      - mqtt.publish_json:
          topic: workbench/testdrive/area-42/evb-ea-ind-02/data.json
          payload: |-
            root["time"] = id(sntp_time).now().timestamp;
            root["bme280_temp"] = id(bme280_temperature).state;
            root["bme280_humidity"] = id(bme280_humidity).state;
            root["bme280_pressure"] = id(bme280_pressure).state;

mqtt:
  broker: daq.example.org
  username: foobar
  password: bazqux
```

### Using `on_time`
```yaml
time:
  - platform: sntp
    id: sntp_time
    on_time:

      # Cron syntax, trigger every 5 minutes
      - cron: '* /5 * * * *'
        then:
          - mqtt.publish_json:
              topic: workbench/testdrive/area-42/evb-ea-ind-02/data.json
              payload: |-
                root["time"] = id(sntp_time).now().timestamp;
                root["bme280_temp"] = id(bme280_temperature).state;
                root["bme280_humidity"] = id(bme280_humidity).state;
                root["bme280_pressure"] = id(bme280_pressure).state;

mqtt:
  broker: daq.example.org
  username: foobar
  password: bazqux
```
